version: "3.7"

services:
    websvc:
        image: rust-websvc:latest
        build:
            context: ../
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        environment:
            SVC_KEY_FILE: "./res/certs/server.key"
            SVC_CERT_FILE: "./res/certs/server.crt"
            SVC_BIND_ADDRESS: "0.0.0.0:8080"
            SVC_NUM_WORKERS: 4
            SVC_SHUTDOWN_TIMEOUT: 10
        volumes:
            # mount the certificate directory as readonly
            - "../res:/home/app/res:ro"
        ports:
            - 8080:8080
